binningfile: binnings/ds3_electron.xml
device: gpu
trainfiles:
  - datasets/dataset_3_1.hdf5
  - datasets/dataset_3_2.hdf5
testfiles:
  - datasets/dataset_3_3.hdf5
  - datasets/dataset_3_4.hdf5
shower_transforms:
  - logit
  - norm
train_val_split: 0.85
batchsize: 8
learning_rate: 4.0e-4
epochs: 100
blocksize_unet: [32, 32, 32, 32]
e_max: 1000.
e_min: 1.
e_log: true
maxdeposit: 2
cylindricalconv: true
phi_image: false
beta_max: 0.02
nsteps: 400
noise_pred_loss: false
stats:
  logit:
    mean: -12.8564
    std: 1.9123
    min: -13.8155
    max: 0.1153
  log:
    mean: -17.5451
    std: 4.4086
    min: -20.0
    max: -0.6372
  sqrt:
    mean: 0.0026
    std: 0.0073
    min: 0.
    max: 1.0